spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: user
    password: password
    properties.mail.smtp:
      auth: true
      starttls.enable: true

#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres