spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true
        required: true

  data.mongodb:
    authentication-database: admin
    username: ${MESSAGE_DB_USER}
    password: ${MESSAGE_DB_PASSWORD}
    database: message
    port: 27017
    host: ${MESSAGE_DB_URL}

sms.client:
  key: ${SMS_CLIENT_KEY}
  secret: ${SMS_CLIENT_SECRET}