version: '3.8'

services:
  db:
    container_name: apartmanager_db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - ../scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql