spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/ApartManager
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  realm: ApartManager
  client-id: apart-manager-be
  base-url: http://localhost:8090/admin/realms/${keycloak.realm}
  token-endpoint: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token/
  user-endpoint: ${keycloak.base-url}/users/
  user-details: ${keycloak.base-url}/protocol/openid-connect/userinfo/
  credentials:
    login: admin
    password: admin

jwt:
  auth:
    converter:
      resource-id: apart-manager-be
