spring:
  datasource:
    url: ${APART_DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${APART_DB_USER:postgres}
    password: ${APART_DB_PASSWORD:postgres}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${AUTH_URL:localhost}:8090/realms/ApartManager
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  realm: ApartManager
  client-id: apart-manager-be
  base-url: http://${AUTH_URL:localhost}:8090/admin/realms/${keycloak.realm}
  token-endpoint: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token/
  user-endpoint: ${keycloak.base-url}/users/
  user-details: ${keycloak.base-url}/protocol/openid-connect/userinfo/
  credentials:
    login: ${KEYCLOAK_USER:admin}
    password: ${KEYCLOAK_PASSWORD:admin}

jwt:
  auth:
    converter:
      resource-id: apart-manager-be

grpc:
  external-integration-service:
    url: ${EXTERNAL_INTEGRATION_SERVICE_URL:localhost}
    port: ${EXTERNAL_INTEGRATION_SERVICE_PORT:6565}
  messaging-service:
    url: ${MESSAGING_SERVICE_URL:localhost}
    port: ${MESSAGING_SERVICE_PORT:6565}