spring:
  datasource:
    url: ${APART_DB_URL}
    username: ${APART_DB_USER}
    password: ${APART_DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/ApartManager
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  realm: ApartManager
  client-id: apart-manager-be
  token-endpoint: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token
  create-user-endpoint: http://localhost:8090/admin/realms/${keycloak.realm}/users
  credentials:
    login: ${KEYCLOAK_USER}
    password: ${KEYCLOAK_PASSWORD}

jwt:
  auth:
    converter:
      resource-id: apart-manager-be
