version: '3.8'

services:
  db:
    container_name: apartmanager_db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes: 
      - ./apartmanager-db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - local

  keycloak_db:
    container_name: apartmanager_keycloak_db
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak_db
      - POSTGRES_PASSWORD=keycloak_db
    ports:
      - "5433:5432"
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    networks:
      - local

  keycloak:
    container_name: apartmanager_auth
    depends_on:
      - keycloak_db
    build: keycloak
    environment:
      KC_DB_PASSWORD: keycloak_db
      KC_DB_URL: jdbc:postgresql://apartmanager_keycloak_db/keycloak
      KC_DB_USERNAME: keycloak_db
      KC_DB: postgres
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8090
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "8090:8090"
    command: ['start-dev', '--http-port=8090', '--import-realm']
    networks:
      - local

  mongo:
    image: mongo
    container_name: messaging-mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  local:
    name: local
    driver: bridge

volumes:
  keycloak-data: #

