name: Azure Apart Manager API Server deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy-apart-manager-server:
    runs-on: ubuntu-latest
    environment: manual
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f Dockerfile-Apart-Manager-Api-Server . \
          -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/apart-manager-server:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/apart-manager-server:${{ github.sha }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}-apart-manager-server
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/apart-manager-server:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: apart-manager-server-polandcentral
          ports: 8080 80
          location: 'polandcentral'
          secure-environment-variables: APART_DB_URL=${{ secrets.APART_DB_URL }} APART_DB_USER="${{ secrets.APART_DB_USER }}" APART_DB_PASSWORD=${{ secrets.APART_DB_PASSWORD }} KEYCLOAK_USER=${{ secrets.KEYCLOAK_USER }} KEYCLOAK_PASSWORD=${{ secrets.KEYCLOAK_PASSWORD }} AUTH_URL=${{ secrets.AUTH_URL }}
