name: Azure Messaging Service deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy-messaging-service:
    runs-on: ubuntu-latest
    environment: manual
    env:
      MAIL_USER: ${{ secrets.MAIL_USER }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MESSAGE_DB_USER: ${{ secrets.MESSAGE_DB_USER }}
      MESSAGE_DB_PASSWORD: ${{ secrets.MESSAGE_DB_PASSWORD }}
      MESSAGE_DB_URL: ${{ secrets.MESSAGE_DB_URL }}
      SMS_CLIENT_KEY: ${{ secrets.SMS_CLIENT_KEY }}
      SMS_CLIENT_SECRET: ${{ secrets.SMS_CLIENT_SECRET }}
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f Dockerfile-Messaging-Service . \
          --secret id=MAIL_USER,env=MAIL_USER \
          --secret id=MAIL_PASSWORD,env=MAIL_PASSWORD \
          --secret id=MESSAGE_DB_USER,env=MESSAGE_DB_USER \
          --secret id=MESSAGE_DB_PASSWORD,env=MESSAGE_DB_PASSWORD \
          --secret id=MESSAGE_DB_URL,env=MESSAGE_DB_URL \
          --secret id=MESSAGE_DB_URL,env=MESSAGE_DB_URL \
          --secret id=SMS_CLIENT_SECRET,env=SMS_CLIENT_SECRET \
          -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/messaging-service:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/messaging-service:${{ github.sha }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}-messaging-service
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/messaging-service:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: messaging-service-polandcentral
          ports: 6565 80
          location: 'polandcentral'